name: Monthly Raw Data Download

on:
  schedule:
    - cron: '0 0 1 * *' # Run on 1st of every month at 00:00 UTC
  workflow_dispatch:

jobs:
  download-and-upload-r2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install pandas requests python-dotenv boto3

      - name: Download and Upload Raw Data
        env:
          DATA_GOV_API_KEY: ${{ secrets.DATA_GOV_API_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: python scripts/download_full_data.py
